# -*- coding: utf-8 -*-
"""T2 flujo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RRZj6SE4_TSE-DMUbdFkEq-ko9NXAOrK
"""
import tareas.T2.tareas_flujo.parametros as R
import pandas as pd
import networkx as nx
import numpy as np
import osmnx as ox



# Se combina en un solo DataFrame todos los tipos de nodo
nodos_totales = pd.concat([nodos_produccion, nodos_bodegas, nodos_demanda], ignore_index=True)

# Se crea un grafo para representar la red en la ciudad
grafo_vial = nx.Graph()

# Se añaden los nodos al grafo
for _, row in nodos_totales.iterrows():
    grafo_vial.add_node(row['id'], id=row['id_mapa'], pos=(row['x'], row['y']), tipo=row['tipo'])

# Se añaden los vertices con distancia entre todos los nodos
for i, nodo_i in nodos_totales.iterrows():
    for j, nodo_j in nodos_totales.iterrows():
        if i < j:  # Evitar duplicados
            distancia = np.sqrt((nodo_i['x'] - nodo_j['x'])**2 + (nodo_i['y'] - nodo_j['y'])**2)
            grafo_vial.add_edge(nodo_i['id_mapa'], nodo_j['id_mapa'], weight=distancia)             # creo que esto debería ser con los nodos dentro del mapa - Vale

# Se crea matriz de costos por transporte
nodos_relevantes = list(grafo_vial.nodes)
num_nodos = len(nodos_relevantes)
matriz_distancias = np.zeros((num_nodos, num_nodos))

# Se llena la matriz
'''for i, nodo_i in enumerate(nodos_relevantes):
    for j, nodo_j in enumerate(nodos_relevantes):
        if i != j:
            matriz_distancias[i, j] = nx.shortest_path_length(grafo_vial, source=nodo_i, target=nodo_j, weight='weight')
'''
# Se define la constante de costo por unidad de distancia
c_tte = 1  # Puedes cambiar este valor según sea necesario

# Se calcula la matriz de costos basada en la matriz de distancias
'''matriz_costos = c_tte * matriz_distancias'''

# Se crea un DataFrame de la matriz de costos
'''matriz_costos_df = pd.DataFrame(matriz_costos, index=nodos_relevantes, columns=nodos_relevantes)'''

# Se muestra la matriz de costos
'''print("Matriz de Costos de Transporte entre Nodos:")
print(matriz_costos_df)'''